---

- name: Install iobroker_required_packages
  pkgng:
    name: "{{ iobroker_required_packages }}"

- name: Create rc.subr file
  template:
    src: FreeBSD.rcd.j2
    dest: "/usr/local/etc/rc.d/{{ iobroker_service }}"
    mode: "0755"
    validate: sh -n %s
  notify:
    - Restart iobroker

- name: Update libnghttp2
  # XXX workaround lib version mismatch
  # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241643
  pkgng:
    name: libnghttp2
    state: latest

- name: Enable iobroker
  service:
    name: "{{ iobroker_service }}"
    enabled: yes
