---
# tasks file for ansible-role-iobroker

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create iobroker_group
  group:
    name: "{{ iobroker_group }}"

- name: Create iobroker_user
  user:
    name: "{{ iobroker_user }}"
    group: "{{ iobroker_group }}"
    groups: "{{ iobroker_groups }}"
    home: "{{ iobroker_dir }}"

- name: Create iobroker_dir
  file:
    path: "{{ iobroker_dir }}"
    state: directory
    owner: "{{ iobroker_user }}"
    group: "{{ iobroker_group }}"

- name: Create .npmrc
  template:
    src: npmrc.j2
    dest: "{{ iobroker_dir }}/.npmrc"
    owner: "{{ iobroker_user }}"
    group: "{{ iobroker_group }}"

- name: Install iobroker
  npm:
    name: "{{ iobroker_npm_package }}"
    registry: "{{ iobroker_npm_registry }}"
    path: "{{ iobroker_dir }}"
    unsafe_perm: yes
  become: yes
  become_user: "{{ iobroker_user }}"
  environment:
    AUTOMATED_INSTALLER: "true"

- name: Install iobroker npm dependencies
  npm:
    registry: "{{ iobroker_npm_registry }}"
    path: "{{ iobroker_dir }}"
    production: yes
    unsafe_perm: yes
  become: yes
  become_user: "{{ iobroker_user }}"
  environment:
    AUTOMATED_INSTALLER: "true"


- name: Start iobroker
  service:
    name: "{{ iobroker_service }}"
    enabled: true
    state: started
